name: Save Commit ID
on:
  workflow_dispatch:

jobs:
  save-commit:
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{ steps.commit_step.outputs.commit_id }}
    steps:
      - name: Get commit ID
        id: commit_step
        run: echo "commit_id=${{ github.sha }}" >> $GITHUB_OUTPUT
