name: Save Commit ID

on: [push]

jobs:
  save-commit-id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get current commit ID
        run: echo "commit_id=${{ github.sha }}" > commit_id.txt

      - name: Save commit ID as artifact
        uses: actions/upload-artifact@v2
        with:
          name: commit-id
          path: commit_id.txt
