name: Save Commit ID
on:
  push:
    branches:
      - main

jobs:
  save-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Save commit ID
        run: echo ${{ github.sha }} > commit_id.txt

      - name: Upload commit ID as artifact
        uses: actions/upload-artifact@v4
        with:
          name: commit-id
          path: commit_id.txt
