name: Save Commit ID
on:
  push:
    branches:
      - main

jobs:
  save-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Save commit ID in GitHub Repository Variable
        run: |
          gh variable set LATEST_COMMIT_ID --body "${{ github.sha }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
