name: Use Commit ID
on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day
  workflow_dispatch:

jobs:
  use-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve Commit ID from Repository Variable
        run: |
          commit_id=$(gh variable get LATEST_COMMIT_ID)
          echo "Commit ID: $commit_id"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
