name: Use Commit ID
on:
  workflow_run:
    workflows: ["Save Commit ID"]
    types:
      - completed

jobs:
  use-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit ID
        run: echo "Commit ID received: ${{ needs.save-commit.outputs.commit_id }}"
