name: Use Commit ID
on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day
  workflow_dispatch:

jobs:
  use-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Download commit ID artifact
        uses: actions/download-artifact@v4
        with:
          name: commit-id

      - name: Read commit ID
        run: |
          commit_id=$(cat commit_id.txt)
          echo "Commit ID: $commit_id"
