name: Use Commit ID
on:
  workflow_run:
    workflows: ["Save Commit ID"]
    types:
      - completed

jobs:
  use-commit:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only runs if previous workflow was successful
    steps:
      - name: Get commit ID
        run: echo "Commit ID received: ${{ needs.save-commit.outputs.commit_id }}"
